local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
---@diagnostic disable-next-line: undefined-field
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	-- require("plugin.monokai"),
	-- require("plugin.onedarkpro"),
	require("plugin.gruvbox"),
	-- require("plugin.gruvboxmat"),
	-- require("plugin.catppuccin"),
	require("plugin.mason"),
	require("plugin.blinkcmp"),
	require("plugin.bufferline"),
	require("plugin.conform"),
	require("plugin.lualine"),
	require("plugin.oil"),
	require("plugin.treesitter"),
	require("plugin.noice"),
	require("plugin.blankline"),
	require("plugin.autopairs"),
	require("plugin.whichkey"),
	require("plugin.project"),
	require("plugin.telescope"),
	require("plugin.comment"),
	require("plugin.minialign"),
	require("plugin.terminal"),
	require("plugin.surround"),
	require("plugin.todo"),
	require("plugin.flash"),
	require("plugin.persistence"),
	require("plugin.luasnip"),
	require("plugin.autotag"),
	require("plugin.neogit"),
	require("plugin.gitsigns"),
	require("plugin.corn"),
	require("plugin.dial"),
	require("plugin.textobjs"),
	require("plugin.yanky"),
	require("plugin.quicker"),
	require("plugin.trouble"),
	require("plugin.markview"),
	require("plugin.precognition"),
	require("plugin.lazydev"),
	require("plugin.roslyn"),
	require("plugin.overseer"),
	-- require("plugin.smartsp"),
	require("plugin.tmuxnavi"),
	require("plugin.dap"),
	require("plugin.leetcode"),
})
